name: Build NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore packages
      run: |
           for s in `find ./CSharp -type f -name "*.sln" -print`; do
               dotnet restore $s
           done

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Build solutions
      run: |
           for s in `find ./CSharp -type f -name "*.sln" -print`; do
               dotnet build --configuration Debug --no-restore $s
           done

    - name: Testing solutions
      run: |
           for s in Patterns-Portfolio-Exercise-WithAccountImplementation PortfolioTreePrinter-Exercise PortfolioTreePrinter-Exercise-WithPortfolioImpl ElevatorExercise ElevatorConsole-Exercise; do
               coverlet CSharp/C2-$s/$s.UnitTests/bin/Debug/net7/$s.UnitTests.dll --target "dotnet" --targetargs "test CSharp/C2-$s/$s.UnitTests/$s.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output $s.coverage.xml
           done

    - name: Upload coverage to CodeCov
      run: bash <(curl -s https://codecov.io/bash)

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./*.coverage.xml

